# Generated by Django 6.0.7 on 2026-07-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Van', 'Van'), ('Truck', 'Truck'), ('Trailer', 'Trailer'), ('Pickup', 'Pickup'), ('Bus', 'Bus')], default='Van', max_length=20)),
                ('max_capacity', models.PositiveIntegerField(help_text='Max load in kg')),
                ('odometer', models.PositiveIntegerField(default=0)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('region', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('In Shop', 'In Shop'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['reg_number'],
            },
        ),
    ]
