# Generated by Django 6.0.7 on 2026-07-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('license_number', models.CharField(max_length=40, unique=True)),
                ('license_category', models.CharField(choices=[('LMV', 'LMV'), ('HMV', 'HMV'), ('HGV', 'HGV'), ('PSV', 'PSV')], default='LMV', max_length=8)),
                ('license_expiry', models.DateField()),
                ('contact', models.CharField(blank=True, max_length=32)),
                ('safety_score', models.PositiveSmallIntegerField(default=80)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('Off Duty', 'Off Duty'), ('Suspended', 'Suspended')], default='Available', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
