# Generated by Django 6.0.7 on 2026-07-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
