# Generated by Django 6.0.7 on 2026-07-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_time_login',
            field=models.BooleanField(default=False),
        ),
    ]
